services:
  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  order_processor:
    build: .
    container_name: order_processor
    command: uvicorn order_processor.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - '8001:8001'
    depends_on:
      - redis
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sns
      - PERSISTENCE=1
    ports:
      - '4566:4566'

volumes:
  localstack_data:
