services:
  fastapi_app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOST=localstack
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sns
    ports:
      - '4566:4566' # LocalStack API Gateway
      - '4510-4559:4510-4559' # To expose SNS for local access

